from typing import Optional
from sqlalchemy.orm import Session
from ..models.user import User
from passlib.context import CryptContext
from ..auth.utils import verify_token
from fastapi import HTTPException, status, Depends
from ..database import get_db
from ..auth.rbac import require_authenticated
from .candidate_service import CandidateService
from .employer_service import EmployerService
from .mfa_service import MFAService
from jose import JWTError, jwt
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from ..auth.schemas import TokenData
from ..config import settings


pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


# Define verify_jwt_token function locally to avoid circular import
security = HTTPBearer()

def verify_jwt_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    try:
        # Decode the JWT token using our own secret key
        payload = jwt.decode(
            token,
            settings.SECRET_KEY,
            algorithms=["HS256"],
        )
        
        # Extract user information from the token
        user_id: str = payload.get("sub")
        user_roles: list = payload.get("roles", [])
        
        if user_id is None:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Could not validate credentials",
                headers={"WWW-Authenticate": "Bearer"},
            )
        
        token_data = TokenData(user_id=user_id, roles=user_roles)
        return token_data
        
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )


class AuthService:
    def __init__(self, db: Session):
        self.db = db

    def get_user_by_id(self, user_id: str) -> Optional[User]:
        """Get user by ID from database"""
        return self.db.query(User).filter(User.id == user_id).first()

    def get_user_by_email(self, email: str) -> Optional[User]:
        """Get user by email from database"""
        return self.db.query(User).filter(User.email == email).first()

    def authenticate_user(self, email: str, password: str) -> Optional[User]:
        """Authenticate user with email and password"""
        user = self.get_user_by_email(email)
        if not user or not self.verify_password(password, user.hashed_password):
            return None
        return user

    def verify_password(self, plain_password: str, hashed_password: str) -> bool:
        """Verify plain password against hashed password"""
        return pwd_context.verify(plain_password, hashed_password)

    def get_password_hash(self, password: str) -> str:
        """Generate password hash, ensuring password doesn't exceed bcrypt's 72-byte limit"""
        # Bcrypt has a 72-byte password length limit
        # Truncate if necessary to avoid ValueError
        if len(password.encode('utf-8')) > 72:
            # For longer passwords, we'll truncate to 72 bytes while preserving the original string meaning
            # Convert to bytes, truncate to 72, then decode back to string
            truncated_password = password.encode('utf-8')[:72].decode('utf-8', errors='ignore')
            return pwd_context.hash(truncated_password)
        return pwd_context.hash(password)

    def create_user(self, email: str, name: str, password: str, role: str) -> User:
        """Create a new user with hashed password"""
        hashed_password = self.get_password_hash(password)
        user = User(
            id=None,  # Will be generated by the database
            email=email,
            name=name,
            hashed_password=hashed_password,
            role=role,
            is_active=True
        )
        self.db.add(user)
        self.db.commit()
        self.db.refresh(user)
        return user

    def get_current_user(self, token_data: TokenData):
        """Get current authenticated user from token data"""
        user_id = token_data.user_id
        user = self.get_user_by_id(user_id)
        if not user:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="User not found",
                headers={"WWW-Authenticate": "Bearer"},
            )
        return user

    def get_current_active_user(self, current_user: User = Depends(get_current_user)):
        """Get current active user"""
        if not current_user.is_active:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Inactive user"
            )
        return current_user


# Dependency to get auth service
def get_auth_service(db: Session = Depends(get_db)):
    return AuthService(db)


# Dependency to get candidate service
def get_candidate_service(db: Session = Depends(get_db)):
    from .candidate_service import CandidateService
    return CandidateService(db)


# Dependency to get employer service
def get_employer_service(db: Session = Depends(get_db)):
    from .employer_service import EmployerService
    return EmployerService(db)


# Dependency to get MFA service
def get_mfa_service(db: Session = Depends(get_db)):
    from .mfa_service import MFAService
    return MFAService(db)